services:
  api:
    image: book-sim
    build:
      context: .
    command: -m uvicorn app.api.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    container_name: book-sim
    volumes:
      - /mnt/books:/books
      - ./data:/data
      - ./app:/app
    environment:
      LIB_URL: https://lib.some.com
      SITE_BASE_PATH: "/similar"
      BOOK_FOLDER: /books/lib.rus.ec
      INPX_FOLDER: /books/librusec_local_fb2.inpx
      DB_FILE: /data/data.db
      INDEX_FILE: /data/index.faiss
      RERANKER_FILE: /data/reranker.lgb
      MODEL_NAME: all-MiniLM-L6-v2
      MAX_WORKERS: 1